services:
  - type: web
    name: minecraft-proxy-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /health
    autoDeploy: true 